graph TD
A([Parent procedure]):::pinkClass --> B1[Process]
A --> B2[Process]
subgraph Process
C1[[subprocess]]--> D1_1{Decision<br/>to be made}
C1--> D1_2{Primary<br/>concepts}
C1--> D1_3{Alternate}
C2[[subprocess]]--> D2_1{Decision <br/>to be made}
C2--> D2_2{Primary<br/>concepts}:::diamondClass
C2--> D2_3{Alternate}

B1-->C1
B2-->C2
end
%%style C1 fill:#f9f,stroke:#333,stroke-width:10px
classDef pinkClass fill:#f99;
classDef diamondClass stroke-width:5px, stroke:#f99, font-size:10px;